### ISSUE TITLE
[llama.cpp convert error] convert.py error

### ISSUE THREAD

**Issue by seohyunjun** [42dot/42dot_LLM#6]
llama.cpp 변환시 [vocab.json](https://huggingface.co/42dot/42dot_LLM-SFT-1.3B/blob/main/vocab.json)의 시작부분이 `{"model":{"vocab":`으로 시작하지 않아 llama.cpp가 읽지를 못해 에러가 발생합니다.

[llama.cpp convert.py # L337](https://github.dev/ggerganov/llama.cpp/blob/62fead3ea0a30c8d424f4a8373fa14165c7c707f/convert.py#L337)
``` python

self.vocab = self.bpe_tokenizer["model"]["vocab"]
#`int' object is not subscriptable
```

아래와 같이 json파일을 수정하고 진행하면 잘 됩니다.
``` 
{"model":{"vocab": ~}}
```

```
python convert.py ./42dot_LLM-SFT-1.3B/ --vocabtype bpe

./quantize ./42dot_LLM-SFT-1.3B/ggml-model-f32.gguf ./42dot_LLM-SFT-1.3B/ggml-model-q4_0.gguf q4_0
```

혹시나 저처럼 vocab.json이 원인인지 모르는 분을 위해 남깁니다. 

좋은 모델 만들어주셔서 감사합니다!.

**Comment by leee-SeungHyeon** [comment]
저도 똑같은 에러가 발생했었습니다.
저는 아래와 같이 수정하여 진행하였습니다.

![image](https://github.com/42dot/42dot_LLM/assets/123627186/91e81043-05f9-423b-b561-71c37d33064d)

기존에는 KeyError만 존재하였지만, TypeError도 같이 넣어주니,

python convert.py ./42dot_LLM-SFT-1.3B/ --vocabtype bpe
해당 코드가 수행되었고, 추후 양자화 변환 및 추론까지 무리없이 수행되었습니다.
감사합니다.

**Comment by seohyunjun** [comment]
`llama.cpp` [history](https://github.com/ggerganov/llama.cpp/pull/5288/commits/15c2df912638d95584dc024e058c536828fb2244) 보니 

추후 수정될 거 같습니다. 👍

**Comment by seohyunjun** [comment]
llama.cpp 5일전 반영 완료

‘’’

        if isinstance(self.bpe_tokenizer.get('model'), dict):
            self.vocab = self.bpe_tokenizer["model"]["vocab"]
        else:
            self.vocab = self.bpe_tokenizer
        added_tokens: dict[str, int]

‘’’
